version: '3'

services:
  consul:
# TODO activate 4 nodes
    command: ["agent", "-server", "-retry-join=10.10.77.61"]
#   command: ["agent", "-server", "-retry-join=10.10.77.61", "-retry-join=10.10.77.62", "-retry-join=10.10.77.63", "-retry-join=10.10.77.64"]
    environment:
        # important: use eth0
        CONSUL_BIND_INTERFACE: eth0
    ports:
        - "8500:8500"
