# static ips v4 from 'cluster' network of dind/compose-file.yml
# bootstrap-expect = N-1 nodes
version: '3'

services:
  consul:
    restart: ""
    command: ["agent", "-server", "-retry-join=10.10.77.61", "-retry-join=10.10.77.62", "-retry-join=10.10.77.63", "-retry-join=10.10.77.64", "-client", "0.0.0.0", "-ui", "-bootstrap-expect=3"]
    environment:
        # important: use eth0
        CONSUL_BIND_INTERFACE: eth0
        CONSUL_UI_BETA: "1"

  haproxy:
    restart: ""
    ports:
      - "80:80"
      - "443:443"
      - "1443:1443"
      - "2244:2244"

  caddy:
    restart: ""
