# static ips v4 from 'cluster' network of dind/compose-file.yml
# bootstrap-expect = N-1 nodes
version: '3'

services:
  consul:
    container_name: cluster_consul_1
    restart: ""
    command: ["agent", "-server", "-retry-join=10.10.77.61", "-retry-join=10.10.77.62", "-retry-join=10.10.77.63", "-retry-join=10.10.77.64", "-client", "0.0.0.0", "-ui", "-bootstrap-expect=3"]
    environment:
        # important: use eth0
        CONSUL_BIND_INTERFACE: eth0
        BTRFSDRIVER: anybox/buttervolume:latest
        CONSUL_LOCAL_CONFIG: '{
           "enable_script_checks": true,
           "watches": [{
               "type": "event",
               "handler_type": "script",
               "args": ["handler", "--logging-config-file", "/home/consul/etc/handler-logging.json"]}]
        }'
    volumes:
      - consul_docker_cfg:/home/consul/.docker
      - ./dind/handler-logging.json:/home/consul/etc/handler-logging.json
      - /run/docker.sock:/run/docker.sock
      - /run/docker/plugins:/run/docker/plugins
      - /deploy:/deploy
      - ./caddy/conf:/consul/template/caddy/:ro
      - caddy_conf:/caddy/:rw
      - ./haproxy/conf:/consul/template/haproxy/:ro
      - haproxy_conf:/haproxy/:rw


  haproxy:
    container_name: cluster_haproxy_1
    restart: ""
    ports:
      - "80:80"
      - "443:443"
      - "1443:1443"
      - "2244:2244"

  caddy:
    container_name: cluster_caddy_1
    restart: ""

  rsyslog:
    container_name: cluster_rsyslog_1

  fluentd:
    container_name: cluster_fluentd_1
    image: fluent/fluentd:stable
    ports:
      - 24224:24224
    volumes:
      - ./dind/fluentd/:/fluentd/etc
