version: '2'
services:
  wordpress:
    environment:
      CADDYFILE: |
        http://test.example.com {
            proxy / http://$CONTAINER:80
        }
        http://www.test.example.com {
            redir http://test.example.com
        }
      PUBKEYS: ssh-rsa 123456 test@example
    build: wordpress
    restart: unless-stopped
    volumes:
      - wwwdata:/var/www/html
      - socket:/var/run/mysqld/
    networks:
      - cluster_default
  wordpress2:
    environment:
      CADDYFILE: |
        https://test.example.com {
            proxy / http://$CONTAINER:80
        }
        https://www.test.example.com {
            redir https://test.example.com
        }
    build: wordpress
    restart: unless-stopped
    volumes:
      - wwwdata:/var/www/html
      - socket:/var/run/mysqld/
    networks:
      - cluster_default
  mariadb:
    image: mariadb:10
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
      - socket:/var/run/mysqld/
    environment:
      MYSQL_ROOT_PASSWORD: "rootpasswd"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "passwd"
  sshservice:
    image: panubo/sshd
    environment:
      HAPROXY: '{
          "ssh-config-name": {
            "frontend": {
              "mode": "tcp",
              "bind": ["*:2222"]
            },
            "backends": [{
              "name": "ssh-service",
              "use_backend_option": "",
              "port": "22",
              "peer_port": "2222"
            }]
          }
        }'
    networks:
      - cluster_default

volumes:
  wwwdata:
    driver: anybox/buttervolume:latest
  dbdata:
    driver: anybox/buttervolume:latest
  socket:

networks:
  cluster_default:
    external: true
